# Generated by Django 3.2.25 on 2024-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=45)),
                ('bookingid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('feedback', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
    ]
