# Generated by Django 3.2.25 on 2024-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.AutoField(primary_key=True, serialize=False)),
                ('notification', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
    ]
