# Generated by Django 3.2.25 on 2024-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistComplaint',
            fields=[
                ('artistcomplaintid', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=500)),
                ('bookingid', models.IntegerField()),
                ('reply', models.CharField(max_length=200)),
                ('artistid', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'artist_complaint',
                'managed': False,
            },
        ),
    ]
