# Generated by Django 3.2.25 on 2024-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistid', models.AutoField(primary_key=True, serialize=False)),
                ('artistname', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('qualification', models.CharField(max_length=45)),
                ('e_mail', models.CharField(db_column='e-mail', max_length=45)),
                ('phone', models.IntegerField()),
                ('image', models.CharField(max_length=500)),
                ('portfolio_image', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'artist',
                'managed': False,
            },
        ),
    ]
