# Generated by Django 3.2.25 on 2024-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('bookingid', models.IntegerField()),
                ('method', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=10)),
                ('cardholder_name', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
