# Generated by Django 3.2.25 on 2024-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('suggestionid', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion', models.CharField(max_length=500)),
                ('userid', models.IntegerField()),
            ],
            options={
                'db_table': 'suggestion',
                'managed': False,
            },
        ),
    ]
